name: Terraform Deployment Pipeline For AWS Batch 73

on:
  pull_request:
    types:
      - closed
    branches:
      - development
      - production
    paths-ignore:
      - 'ReadMe.md'

  push:
    branches:
      - development
      - production
    paths-ignore:
      - 'ReadMe.md'


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ENV_DESTROY: "YES"
  TERRAFORM_DESTROY: ${{ vars.TERRAFORM_DESTROY }}
  TERRAFORM_VERSION: "1.13.4"


jobs:
  terraform-checkov:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage 1 - Checkov Security Scanning For Terraform Code'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5

      - name: Print Runner Hostname
        run: echo $HOSTNAME

      - name: Setup Checkov For Security Scanning
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./TerraformWorkspaces/Alpha-Bravo
          quiet: true
          soft_fail: true
          output_format: cli,json
          output_file_path: console,./TerraformWorkspaces/Alpha-Bravo/results.json

      - name: Upload Checkov Results to S3 Bucket
        run: |
          aws s3 cp ./TerraformWorkspaces/Alpha-Bravo/results.json s3://awsb73-terraform-modules-bucket/checkov-results/results.json