name: Terraform Deployment Pipeline For AWS Batch 73
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - development
      - production
    paths-ignore:
      - 'ReadMe.md'
  push:
    branches:
      - development
      - production
    paths-ignore:
      - 'ReadMe.md'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ENV_DESTROY: "YES"
  TERRAFORM_DESTROY: ${{ vars.TERRAFORM_DESTROY }}
  TERRAFORM_VERSION: "1.14.0"

jobs:

  terraform-checkov:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage 1 - Checkov Security Scanning For Terraform Code'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Setup Checkov For Security Scanning
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./TerraformWorkspaces/Alpha-Bravo
          quiet: true
          soft_fail: true
          output_format: cli,json
          output_file_path: console,./TerraformWorkspaces/Alpha-Bravo/results.json
      - name: Upload Checkov Results to S3 Bucket
        run: |
          aws s3 cp ./results.json s3://awsb73-terraform-modules-bucket/checkov-results/results.json

  terraform-initiate:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage 2 - Terraform Initialization'
    runs-on: ubuntu-latest
    needs: terraform-checkov
    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Init, Format, Validate
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: Creating Terraform Workspaces
        run: |
          terraform workspace select development || terraform workspace new development
          terraform workspace select production || terraform workspace new production
      - name: List Terraform Workspaces
        run: terraform workspace list

  terraform-plan:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage 3 - Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform-initiate
    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Init, Format, Validate
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: Print Branch Reference
        run: echo "The Current Branch Is $GITHUB_REF"
      - name: Terraform Plan
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/development" ]; then
            echo "Running Terraform Plan For Development Environment"
            terraform workspace select development
            terraform plan --var-file=Bravo.tfvars
          elif [ "${GITHUB_REF}" == "refs/heads/production" ]; then
            echo "Running Terraform Plan For Production Environment"
            terraform workspace select production
            terraform plan --var-file=Alpha.tfvars
          else
            echo "Nothing Is Deployed As The Branch Is Not Development or Production."
            exit 1
          fi

  terraform-apply:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage 4 - Terraform Apply For Production'
    runs-on: ubuntu-latest
    needs: terraform-plan
    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Init, Format, Validate
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: Terraform Apply
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/development" ]; then
            echo "Running Terraform Apply For Development Environment"
            terraform workspace select development
            terraform apply --var-file=Bravo.tfvars -auto-approve
          elif [ "${GITHUB_REF}" == "refs/heads/production" ]; then
            echo "Running Terraform Apply For Production Environment"
            terraform workspace select production
            terraform apply --var-file=Alpha.tfvars -auto-approve
          else
            echo "Nothing Is Deployed As The Branch Is Not Development or Production."
            exit 1
          fi

  terraform-destroy:
    if: ${{ vars.TERRAFORM_DESTROY == 'YES' }}
    name: 'Stage 5 - Terraform Destroy Production Resources'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TerraformWorkspaces/Alpha-Bravo
    steps:
      - name: Checkout The Code Repository
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Init, Format, Validate
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: Terraform Destroy
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/development" ]; then
            echo "Running Terraform Destroy For Development Environment"
            terraform workspace select development
            terraform destroy --var-file=Bravo.tfvars -auto-approve
          elif [ "${GITHUB_REF}" == "refs/heads/production" ]; then
            echo "Running Terraform Destroy For Production Environment"
            terraform workspace select production
            terraform destroy --var-file=Alpha.tfvars -auto-approve
          else
            echo "Nothing Is Destroyed As The Branch Is Not Development or Production."
            exit 1
          fi
